[package]
name = "task-ping"
version = "0.1.0"
authors = ["Cliff L. Biffle <cliff@oxide.computer>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.6.0"
userlib = {path = "../userlib"}
stm32f4 = {version = "0.10.0", features = ["stm32f407"]}

[features]
default = ["standalone"]
standalone = []

[[bin]]
name = "task-ping"
test = false
bench = false
