name = "demo"
target = "thumbv7em-none-eabihf"

[kernel]
path = "../demo"
name = "demo"
requires = {flash = 65536, ram = 4096}

[outputs.flash]
address = 0x08000000
size = 262144
read = true
execute = true

[outputs.ram]
address = 0x20000000
size = 114688
read = true
write = true
execute = true

[tasks.rcc-driver]
path = "../drv/stm32f4-rcc"
name = "drv-stm32f4-rcc"
priority = 0
requires = {flash = 8192, ram = 1024}
uses = ["rcc"]
start = true

[tasks.ping]
path = "../task-ping"
name = "task-ping"
priority = 2
requires = {flash = 2048, ram = 512}
uses = ["gpiod"]
start = true

[tasks.pong]
path = "../task-pong"
name = "task-pong"
priority = 1
requires = {flash = 8192, ram = 512}
uses = ["gpiod"]
start = true

[peripherals.rcc]
address = 0x40023800
size = 1024

[peripherals.gpiod]
address = 0x40020c00
size = 1024
