name = "demo"
target = "thumbv7em-none-eabihf"

[kernel]
path = "../demo"
name = "demo"
requires = {flash = 65536, ram = 4096}
features = ["semihosting"]

[outputs.flash]
address = 0x08000000
size = 262144
read = true
execute = true

[outputs.ram]
address = 0x20000000
size = 114688
read = true
write = true
execute = true

[tasks.rcc_driver]
path = "../drv/stm32f4-rcc"
name = "drv-stm32f4-rcc"
priority = 0
requires = {flash = 8192, ram = 1024}
uses = ["rcc"]
start = true

[tasks.usart_driver]
path = "../drv/stm32f4-usart"
name = "drv-stm32f4-usart"
priority = 1
requires = {flash = 8192, ram = 1024}
uses = ["usart2", "gpioa"]
start = true
interrupts = {38 = 1}

[tasks.ping]
path = "../task-ping"
name = "task-ping"
priority = 2
requires = {flash = 8192, ram = 512}
uses = ["gpiod"]
start = true

[tasks.pong]
path = "../task-pong"
name = "task-pong"
priority = 1
requires = {flash = 8192, ram = 1024}
uses = ["gpiod"]
start = true

[tasks.idle]
path = "../task-idle"
name = "task-idle"
priority = 3
requires = {flash = 256, ram = 256}
start = true

[peripherals.usart2]
address = 0x40004400
size = 1024

[peripherals.rcc]
address = 0x40023800
size = 1024

[peripherals.gpioa]
address = 0x40020000
size = 1024

[peripherals.gpiod]
address = 0x40020c00
size = 1024
